import { Platform, StyleSheet, type TextStyle, type ViewStyle } from 'react-native';

import { Radius } from '@/constants/theme';

export const depositStyles = {
  flex: {
    flex: 1,
  },
  sheetBody: {
    paddingHorizontal: 20,
    gap: 14,
  },
  sheetFullScreen: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 20,
    gap: 14,
  },
  momoScroll: {
    gap: 14,
    paddingBottom: 24,
    flexGrow: 1,
  },
  sheetContainer: {
    paddingHorizontal: 0,
    gap: 0,
  },
  sheetTall: {
    minHeight: '78%',
  },
  handle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(120,120,120,0.35)',
    marginBottom: 4,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 36,
    gap: 8,
  },
  sheetTitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 20,
    fontWeight: '700',
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backBtn: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  methodList: {
    gap: 10,
    paddingBottom: 8,
  },
  methodCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: Radius.lg,
    borderWidth: StyleSheet.hairlineWidth,
  },
  methodTitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 17,
    fontWeight: '700',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metaText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 13,
    fontWeight: '500',
  },
  metaDot: {
    marginHorizontal: 2,
    fontSize: 13,
  },
  iconStack: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconStackItem: {
    borderRadius: 999,
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  detailContent: {
    gap: 14,
    paddingBottom: 12,
  },
  qrFrame: {
    alignSelf: 'center',
    padding: 16,
    borderRadius: Radius.lg,
  },
  addressBox: {
    borderRadius: Radius.md,
    padding: 14,
    gap: 8,
  },
  addressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  addressLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 13,
    fontWeight: '500',
  },
  addressValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 20,
    fontWeight: '700',
  },
  addressValueMono: {
    fontSize: 15,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontWeight: '600',
    lineHeight: 22,
  },
  copyLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  copyLinkText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    fontWeight: '700',
  },
  infoBanner: {
    flexDirection: 'row',
    gap: 10,
    padding: 14,
    borderRadius: Radius.md,
    alignItems: 'flex-start',
  },
  infoTitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    fontWeight: '700',
  },
  infoBody: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '400',
  },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 15,
    borderRadius: Radius.pill,
    marginTop: 4,
  },
  primaryBtnText: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    fontWeight: '700',
  },
  fieldLabel: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 13,
    fontWeight: '500',
    marginBottom: -6,
  },
  selectField: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: Radius.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 52,
  },
  selectLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  selectValue: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    fontWeight: '700',
  },
  assetRow: {
    flexDirection: 'row',
    gap: 8,
  },
  assetChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: Radius.pill,
  },
  inputFlex: {
    flex: 1,
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    fontWeight: '600',
    paddingVertical: 0,
  },
  pickerList: {
    gap: 10,
    paddingBottom: 12,
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: Radius.md,
  },
  pickerTitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 16,
    fontWeight: '700',
  },
  pickerSub: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 13,
    fontWeight: '400',
    marginTop: 2,
  },
  feeAlert: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    padding: 12,
    borderRadius: Radius.md,
  },
  feeAlertText: {
    flex: 1,
    fontFamily: 'DMSans_400Regular',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
  },
  momoStatusBody: {
    flex: 1,
    gap: 20,
    paddingTop: 24,
    justifyContent: 'center',
  },
  awaitingHero: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
  },
  awaitingTitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
  },
  awaitingAmount: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 32,
    fontWeight: '700',
    marginTop: 4,
  },
  awaitingMeta: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  awaitingExpiry: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 13,
    fontWeight: '500',
    textAlign: 'center',
  },
  successHero: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  successIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  successTitle: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
  },
  successAmount: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 34,
    fontWeight: '700',
    textAlign: 'center',
    width: '100%',
  },
} satisfies Record<string, ViewStyle | TextStyle>;
