/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a9fbca58b8176c5009ab48dc44c2a27f)
interface __BaseEnv_Env {
	PAYROLL_ATTACHMENTS: R2Bucket;
	TRANSACTIONAL_EMAIL_QUEUE: Queue;
	GMAIL_SYNC_QUEUE: Queue;
	CALENDAR_SYNC_QUEUE: Queue;
	ENVIRONMENT: "development";
	CLERK_PUBLISHABLE_KEY: "pk_test_b3Blbi1vY3RvcHVzLTMuY2xlcmsuYWNjb3VudHMuZGV2JA";
	WELCOME_EMAIL_FROM: "Finora <welcome@mail.askorin.app>";
	WELCOME_EMAIL_REPLY_TO: "hello@askorin.app";
	WELCOME_EMAIL_CTA_URL: "https://askorin.app";
	WEWIRE_API_KEY: string;
	WEWIRE_WEBHOOK_SECRET: string;
	DATABASE_URL: string;
	DATABASE_URL_UNPOOLED: string;
	AGOO_SMS_API_KEY: string;
	AGOO_SMS_SENDER_ID: string;
	CLERK_SECRET_KEY: string;
	RESEND_API_KEY: string;
	WELCOME_EMAIL_MODE: string;
	CLERK_WEBHOOK_SIGNING_SECRET: string;
	RESEND_WEBHOOK_SECRET: string;
	DEEPGRAM_API_KEY: string;
	OPENAI_API_KEY: string;
	REDIS_URL: string;
	OPENROUTER_API_KEY: string;
	OPENROUTER_MODEL: string;
	GOOGLE_OAUTH_CLIENT_ID: string;
	GOOGLE_OAUTH_CLIENT_SECRET: string;
	GOOGLE_OAUTH_REDIRECT_URI: string;
	GOOGLE_TOKEN_ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "CLERK_PUBLISHABLE_KEY" | "WELCOME_EMAIL_FROM" | "WELCOME_EMAIL_REPLY_TO" | "WELCOME_EMAIL_CTA_URL" | "WEWIRE_API_KEY" | "WEWIRE_WEBHOOK_SECRET" | "DATABASE_URL" | "DATABASE_URL_UNPOOLED" | "AGOO_SMS_API_KEY" | "AGOO_SMS_SENDER_ID" | "CLERK_SECRET_KEY" | "RESEND_API_KEY" | "WELCOME_EMAIL_MODE" | "CLERK_WEBHOOK_SIGNING_SECRET" | "RESEND_WEBHOOK_SECRET" | "DEEPGRAM_API_KEY" | "OPENAI_API_KEY" | "REDIS_URL" | "OPENROUTER_API_KEY" | "OPENROUTER_MODEL" | "GOOGLE_OAUTH_CLIENT_ID" | "GOOGLE_OAUTH_CLIENT_SECRET" | "GOOGLE_OAUTH_REDIRECT_URI" | "GOOGLE_TOKEN_ENCRYPTION_KEY">> {}
}
