/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c9386e24b205de995b56ca53e753cdb6)
interface __BaseEnv_Env {
  TRANSACTIONAL_EMAIL_QUEUE: Queue;
  ENVIRONMENT: 'development';
  CLERK_PUBLISHABLE_KEY: 'pk_test_b3Blbi1vY3RvcHVzLTMuY2xlcmsuYWNjb3VudHMuZGV2JA';
  WELCOME_EMAIL_FROM: 'Finora <welcome@mail.askorin.app>';
  WELCOME_EMAIL_REPLY_TO: 'hello@askorin.app';
  WELCOME_EMAIL_CTA_URL: 'https://askorin.app';
  WEWIRE_API_KEY: string;
  WEWIRE_WEBHOOK_SECRET: string;
  DATABASE_URL: string;
  DATABASE_URL_UNPOOLED: string;
  AGOO_SMS_API_KEY: string;
  AGOO_SMS_SENDER_ID: string;
  CLERK_SECRET_KEY: string;
  RESEND_API_KEY: string;
  OPENAI_API_KEY: string;
  REDIS_URL: string;
  WELCOME_EMAIL_MODE: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'ENVIRONMENT'
      | 'CLERK_PUBLISHABLE_KEY'
      | 'WELCOME_EMAIL_FROM'
      | 'WELCOME_EMAIL_REPLY_TO'
      | 'WELCOME_EMAIL_CTA_URL'
      | 'WEWIRE_API_KEY'
      | 'WEWIRE_WEBHOOK_SECRET'
      | 'DATABASE_URL'
      | 'DATABASE_URL_UNPOOLED'
      | 'AGOO_SMS_API_KEY'
      | 'AGOO_SMS_SENDER_ID'
      | 'CLERK_SECRET_KEY'
      | 'RESEND_API_KEY'
      | 'WELCOME_EMAIL_MODE'
    >
  > {}
}
