/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false` (hash: ed6e8c1f6820caf49c15c171551713a9)
interface __BaseEnv_Env {
  TRANSACTIONAL_EMAIL_QUEUE: Queue;
  ENVIRONMENT: string;
  WELCOME_EMAIL_FROM: string;
  WELCOME_EMAIL_REPLY_TO: string;
  WELCOME_EMAIL_CTA_URL: string;
  WEWIRE_API_KEY: string;
  CLERK_SECRET_KEY: string;
  CLERK_PUBLISHABLE_KEY: string;
  CLERK_WEBHOOK_SIGNING_SECRET: string;
  DEEPGRAM_API_KEY: string;
  OPENAI_API_KEY: string;
  REDIS_URL: string;
  DATABASE_URL: string;
  DATABASE_URL_UNPOOLED: string;
  RESEND_API_KEY: string;
  RESEND_WEBHOOK_SECRET: string;
  WELCOME_EMAIL_MODE: string;
  WELCOME_EMAIL_REDIRECT_TO: string;
  AGOO_SMS_API_KEY: string;
  AGOO_SMS_SENDER_ID: string;
  WEWIRE_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'ENVIRONMENT'
      | 'WELCOME_EMAIL_FROM'
      | 'WELCOME_EMAIL_REPLY_TO'
      | 'WELCOME_EMAIL_CTA_URL'
      | 'WEWIRE_API_KEY'
      | 'CLERK_SECRET_KEY'
      | 'CLERK_PUBLISHABLE_KEY'
      | 'CLERK_WEBHOOK_SIGNING_SECRET'
      | 'DEEPGRAM_API_KEY'
      | 'OPENAI_API_KEY'
      | 'REDIS_URL'
      | 'DATABASE_URL'
      | 'DATABASE_URL_UNPOOLED'
      | 'RESEND_API_KEY'
      | 'RESEND_WEBHOOK_SECRET'
      | 'WELCOME_EMAIL_MODE'
      | 'WELCOME_EMAIL_REDIRECT_TO'
      | 'AGOO_SMS_API_KEY'
      | 'AGOO_SMS_SENDER_ID'
      | 'WEWIRE_WEBHOOK_SECRET'
    >
  > {}
}
