import { useAui } from '@assistant-ui/react-native';
import { useAuth } from '@clerk/expo';
import { LegendList } from '@legendapp/list/react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet, TextInput, View } from 'react-native';
import { Gesture, GestureDetector } from 'react-native-gesture-handler';
import Animated, { runOnJS, useAnimatedStyle, useSharedValue, withSpring, withTiming } from 'react-native-reanimated';

import { formatPaymentAmount } from '@/components/chat/PaymentConfirmationCard';
import { Icon } from '@/components/ui/icon';
import { LoadingIcon } from '@/components/ui/loading-icon';
import { SheetModal } from '@/components/ui/sheet-modal';
import { AppText as Text } from '@/components/ui/text';
import { Radius } from '@/constants/theme';
import { useTheme } from '@/hooks/use-theme';
import { isBusinessAccount } from '@/lib/account';
import { haptics } from '@/lib/haptics';
import { deletePayrollRow, listPayrollImports, type PayrollImport, updatePayrollRow } from '@/lib/payroll-api';

type Row = PayrollImport['rows'][number];
type Colors = ReturnType<typeof useTheme>['colors'];

export default function PayrollScreen() {
  const { colors } = useTheme();
  const { getToken } = useAuth();
  const router = useRouter();
  const aui = useAui();
  const [imports, setImports] = useState<PayrollImport[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [selected, setSelected] = useState<{ importId: string; row: Row } | null>(null);
  const refresh = useCallback(async () => { try { setError(null); setImports(await listPayrollImports(getToken)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load payroll imports.'); setImports([]); } }, [getToken]);
  useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  if (!isBusinessAccount()) return <View style={[styles.root, { backgroundColor: colors.background }]}><Text style={[styles.title, { color: colors.foreground }]}>Payroll</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Payroll is available on Business accounts.</Text></View>;
  if (!imports) return <View style={[styles.root, { backgroundColor: colors.background }]}><LoadingIcon style={{ marginTop: 40 }} color={colors.mutedForeground} /></View>;
  const save = async (patch: Record<string, unknown>) => { if (!selected) return; const key = `${selected.importId}:${selected.row.rowId}`; setBusy(key); try { const updated = await updatePayrollRow(selected.importId, selected.row.rowId, patch, getToken); setImports((current) => current?.map((item) => item.id === updated.id ? updated : item) ?? current); const row = updated.rows.find((candidate) => candidate.rowId === selected.row.rowId); if (row) setSelected({ importId: selected.importId, row }); haptics.success(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save payroll employee.'); } finally { setBusy(null); } };
  const remove = async (importId: string, rowId: string) => { const key = `${importId}:${rowId}`; setBusy(key); try { const updated = await deletePayrollRow(importId, rowId, getToken); setImports((current) => current?.map((item) => item.id === updated.id ? updated : item) ?? current); if (selected?.row.rowId === rowId) setSelected(null); haptics.success(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not delete payroll employee.'); } finally { setBusy(null); } };
  return <><LegendList data={imports} keyExtractor={(item) => item.id} recycleItems showsVerticalScrollIndicator={false} style={[styles.root, { backgroundColor: colors.background }]} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><Text style={[styles.title, { color: colors.foreground }]}>Payroll</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Tap an employee to edit. Swipe left or use the delete icon to remove them.</Text>{error ? <Text style={[styles.error, { color: colors.destructive }]}>{error}</Text> : null}<Pressable onPress={() => { haptics.selection(); router.push('/'); aui.composer.setText('Create a payroll from an attachment'); }} style={[styles.btn, { backgroundColor: colors.foreground }]}><Text style={[styles.btnLabel, { color: colors.background }]}>Create payroll in chat</Text></Pressable></View>} ListEmptyComponent={<View style={[styles.empty, { borderColor: colors.border, backgroundColor: colors.composer }]}><Text style={{ color: colors.mutedForeground }}>No payroll imports yet. Attach a payroll file in chat to create one.</Text></View>} ItemSeparatorComponent={() => <View style={styles.separator} />} renderItem={({ item }) => <ImportCard item={item} colors={colors} busy={busy} onOpen={(row) => setSelected({ importId: item.id, row })} onDelete={(rowId) => void remove(item.id, rowId)} />}/><Editor selected={selected} colors={colors} busy={selected ? busy === `${selected.importId}:${selected.row.rowId}` : false} onClose={() => setSelected(null)} onSave={save} /></>;
}

function ImportCard({ item, colors, busy, onOpen, onDelete }: { item: PayrollImport; colors: Colors; busy: string | null; onOpen: (row: Row) => void; onDelete: (rowId: string) => void }) { return <View style={[styles.card, { borderColor: colors.border, backgroundColor: colors.composer }]}><View style={styles.cardHeader}><View style={styles.rowText}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{item.sourceName}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{item.rows.length} employees Â· {item.status} Â· {item.period ?? 'Period not set'}</Text></View><Text style={[styles.total, { color: colors.foreground }]}>{formatPaymentAmount(item.total, item.currency)}</Text></View>{item.rows.map((row) => <EmployeeRow key={row.rowId} row={row} colors={colors} busy={busy === `${item.id}:${row.rowId}`} onOpen={() => onOpen(row)} onDelete={() => onDelete(row.rowId)} />)}{item.blockingIssues.length ? <Text style={[styles.error, { color: colors.destructive }]}>{item.blockingIssues.length} issue{item.blockingIssues.length === 1 ? '' : 's'} must be fixed before preparation.</Text> : null}</View>; }

function EmployeeRow({ row, colors, busy, onOpen, onDelete }: { row: Row; colors: Colors; busy: boolean; onOpen: () => void; onDelete: () => void }) { const x = useSharedValue(0); const remove = () => { x.value = withTiming(-420, { duration: 180 }, (done) => { if (done) runOnJS(onDelete)(); }); }; const pan = Gesture.Pan().activeOffsetX([-12, 12]).failOffsetY([-12, 12]).onUpdate((e) => { x.value = Math.min(0, e.translationX); }).onEnd((e) => { if (e.translationX < -110 || e.velocityX < -700) runOnJS(remove)(); else x.value = withSpring(0); }); const animated = useAnimatedStyle(() => ({ transform: [{ translateX: x.value }] })); return <View style={styles.swipeFrame}><View style={[styles.deleteReveal, { backgroundColor: colors.destructive }]}><Icon name='remove' size={20} color='#fff' /></View><GestureDetector gesture={pan}><Animated.View style={[styles.employeeRow, { borderTopColor: colors.border, backgroundColor: colors.composer }, animated]}><Pressable disabled={busy} onPress={onOpen} style={styles.rowPress}><View style={styles.avatar}><Text style={[styles.avatarText, { color: colors.foreground }]}>{(row.employeeName ?? '?').slice(0, 1).toUpperCase()}</Text></View><View style={styles.rowText}><Text style={[styles.name, { color: colors.foreground }]}>{row.employeeName ?? 'Unnamed employee'}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{row.role || row.destinationType || 'Payroll employee'} Â· {row.currency ?? ''} {row.amount?.toLocaleString() ?? 'â€”'}</Text></View></Pressable><Pressable accessibilityRole='button' accessibilityLabel={`Delete ${row.employeeName ?? 'employee'}`} disabled={busy} onPress={onDelete} style={styles.deleteButton}><Icon name='remove' size={18} color={colors.destructive} /></Pressable></Animated.View></GestureDetector></View>; }

function Editor({ selected, colors, busy, onClose, onSave }: { selected: { importId: string; row: Row } | null; colors: Colors; busy: boolean; onClose: () => void; onSave: (patch: Record<string, unknown>) => Promise<void> }) { const row = selected?.row; const [values, setValues] = useState<Record<string, string>>({}); useEffect(() => { if (row) setValues({ employeeName: row.employeeName ?? '', employeeId: row.employeeId ?? '', role: row.role ?? '', amount: row.amount == null ? '' : String(row.amount), currency: row.currency ?? '', destinationType: row.destinationType ?? '', destination: row.destination ?? '', rail: row.rail ?? '', period: row.period ?? '', payDate: row.payDate ?? '', reference: row.reference ?? '' }); }, [row]); const fields: Array<[string, string]> = [['employeeName','Name'],['employeeId','Employee ID'],['role','Position'],['amount','Amount'],['currency','Currency'],['destinationType','Destination type'],['destination','Destination'],['rail','Network / bank'],['period','Pay period'],['payDate','Pay date (YYYY-MM-DD)'],['reference','Reference']]; return <SheetModal visible={Boolean(row)} onClose={onClose} keyboardAvoiding style={styles.sheet}><View style={styles.sheetHeader}><View><Text style={[styles.sheetTitle, { color: colors.foreground }]}>Employee details</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>Edit imported payroll information</Text></View><Pressable onPress={onClose}><Icon name='close-circle' size={22} color={colors.mutedForeground} /></Pressable></View>{row ? <View style={styles.form}>{fields.map(([key, label]) => <TextInput key={key} value={values[key] ?? ''} onChangeText={(value) => setValues((current) => ({ ...current, [key]: value }))} placeholder={label} placeholderTextColor={colors.mutedForeground} keyboardType={key === 'amount' ? 'decimal-pad' : 'default'} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} />)}<Pressable disabled={busy} onPress={() => void onSave({ ...values, amount: Number(values.amount), payDate: values.payDate || null })} style={[styles.saveButton, { backgroundColor: colors.foreground, opacity: busy ? 0.6 : 1 }]}><Text style={{ color: colors.background }}>{busy ? 'Savingâ€¦' : 'Save changes'}</Text></Pressable></View> : null}</SheetModal>; }

const styles = StyleSheet.create({ root: { flex: 1 }, content: { padding: 20, paddingBottom: 40 }, header: { gap: 10, paddingBottom: 10 }, title: { fontSize: 25, fontWeight: '600' }, subtitle: { fontSize: 15, lineHeight: 20 }, separator: { height: 12 }, empty: { padding: 16, borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.card }, card: { padding: 16, borderWidth: StyleSheet.hairlineWidth, borderRadius: Radius.card, gap: 4 }, cardHeader: { flexDirection: 'row', gap: 12, alignItems: 'center', marginBottom: 4 }, cardTitle: { fontSize: 16, fontWeight: '700' }, rowText: { flex: 1, minWidth: 0 }, total: { fontSize: 16, fontWeight: '700' }, meta: { fontSize: 13 }, name: { fontSize: 15, fontWeight: '600' }, error: { fontSize: 13, lineHeight: 18, marginTop: 10 }, employeeRow: { minHeight: 64, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 8 }, rowPress: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10 }, avatar: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E7E2D9' }, avatarText: { fontSize: 14, fontWeight: '700' }, swipeFrame: { overflow: 'hidden' }, deleteReveal: { ...StyleSheet.absoluteFillObject, alignItems: 'flex-end', justifyContent: 'center', paddingRight: 20 }, deleteButton: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center' }, btn: { minHeight: 44, borderRadius: Radius.composer, alignItems: 'center', justifyContent: 'center', marginTop: 4 }, btnLabel: { fontSize: 15, fontWeight: '600' }, sheet: { paddingHorizontal: 20, paddingBottom: 28 }, sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingBottom: 14 }, sheetTitle: { fontSize: 20, fontWeight: '700' }, form: { gap: 10 }, input: { minHeight: 44, borderWidth: StyleSheet.hairlineWidth, borderRadius: 10, paddingHorizontal: 12, fontSize: 15 }, saveButton: { minHeight: 46, borderRadius: Radius.composer, alignItems: 'center', justifyContent: 'center', marginTop: 4 } });
